---
title: "Projekt_Variablen"
author: "Peyman Farshidfar"
date: "10 5 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r}

# Import needed libraries
library(readr)
library(lubridate)
library(ggplot2)
library(dplyr)
library(tidyverse)
# Import turnover data
umsatzdaten <- read_csv("https://raw.githubusercontent.com/opencampus-sh/einfuehrung-in-data-science-und-ml/main/umsatzdaten_gekuerzt.csv")
wetter <- read_csv("https://raw.githubusercontent.com/opencampus-sh/einfuehrung-in-data-science-und-ml/main/wetter.csv")
kiwo <- read_csv("https://raw.githubusercontent.com/opencampus-sh/einfuehrung-in-data-science-und-ml/main/kiwo.csv")
wetter_dwd <- read_delim("wetter_dwd.csv", delim = ";")


fullData <- merge(umsatzdaten,kiwo, by="Datum")

fullData <- merge(fullData,wetter, by="Datum")



```
```{r html aus einem String entfernen}
cleanFun <- function(htmlString) {
  return(gsub("<.*?>", "", htmlString))
}
```




```{r Daten aus einer Kalender Webseite Teil 1, Alle Jahre im Datensatz ermitteln}

#Herausfiltern aller Jahre im Datensatz:

#Nur das Jahr mit substr(x, start, stop)
#substr(umsatzdaten$Datum, start, stop)
#z.B. 2013-07-01  
#     12345678910
#substr(umsatzdaten$Datum, 1, 4)
allYears <- unique(substr(umsatzdaten$Datum, 1, 4))


#print(allYears)
#Ausgabe: [1] "2013" "2014" "2015" "2016" "2017" "2018" "2019"

```



```{r Daten aus einer Kalender Webseite Teil 2, Installation der Packages}
install.packages(rvest)
install.packages(xml2)
install.packages(stringr)
install.packages(XML)
#Hat bei mir nur manuell funktioniert
```


```{r Daten aus einer Kalender Webseite Teil 3, Einbinden der Packages}

library(rvest)
library(xml2)
library(stringr) 

```













```{r Feiertage}


feiertage <- data.frame(matrix(ncol = 3, nrow = 0))
for(i in allYears){
  

testJahr = i;

site = paste("https://www.schulferien.org/Kalender_mit_Ferien/kalender_",testJahr,"_ferien_Schleswig_Holstein.html");

site = str_replace_all(site," ", "")

print(site);
test = read_html(site)


test <- test %>% 
  html_nodes(".feiertag_liste") %>%
  html_text() %>% 
  .[1]

test = str_replace_all(test,"\n", "")

string1 = str_replace(paste("              ",testJahr)," ", "");
print(string1)

string2 = str_replace(paste(".",testJahr)," ", "");

print(string2)

test = str_replace_all(test,string1, string2)

test = str_replace_all(test,"                                    ", "")
test = str_replace_all(test,"   ", "")

test = str_replace_all(test,"Jan", "01")
test = str_replace_all(test,"Feb", "02")
test = str_replace_all(test,"Mär", "03")
test = str_replace_all(test,"Apr", "04")
test = str_replace_all(test,"Mai", "05")
test = str_replace_all(test,"Jun", "06")
test = str_replace_all(test,"Jul", "07")
test = str_replace_all(test,"Aug", "08")
test = str_replace_all(test,"Sep", "09")
test = str_replace_all(test,"Okt", "10")
test = str_replace_all(test,"Nov", "11")
test = str_replace_all(test,"Dez", "12")

test = str_replace_all(test,"  ", ";")

print(test)


test = str_replace_all(test," ", "")  



rs <- (test)
rs = strsplit(rs, split = ";")
print(rs)

print(typeof(rs))


rs <-unlist(rs, use.names=FALSE);

print(rs)

print(test)


Datum <- vector();
Feiertag <- vector();
Jahr <- vector();

j = 1;
for(i in rs){
  if((j %% 2) != 0){
    Datum <- append(Datum,i);
    Jahr <- append(Jahr,testJahr);
  }else{
    Feiertag <- append(Feiertag,i);
    
  }
  j = j + 1;
}

Datum <- as.Date(Datum,format = "%d.%m.%y")

feiertage <- rbind(feiertage,data.frame(Jahr,Datum,Feiertag))

}


```







































































































```{r Daten aus einer Kalender Webseite Teil 4 Keine Gute Seite}
# https://www.schnelle-online.info/Schleswig-Holstein/Feiertage-Schleswig-Holstein-2016.html


#Vektoren für die URL jeweils für URL und html Inhalt erstellen:
#vector_url <- c()
#vector_inhalt <- c()
#Data-Frame erstellen für die Datenspeicherung der Webseite
#websiteData <- data.frame(allYears, vector_url, vector_inhalt)
websiteData <- data.frame(matrix(ncol = 3, nrow = 0))
#Spalten benennen
colnames(websiteData) <- c('Jahr', 'URL', 'Webseiteninhalt')


#For-Schleife um jedes Jahr in allYears zu durchlaufen
i = 1
for(Jahre in allYears){
#Mit paste() Strings zusammensetzen  Url+ Jahreszahl aus der Variable allYears + rest der URL
#paste(String1,String2,String3)= String1String2String3  
    site=paste("https://www.schnelle-online.info/Schleswig-Holstein/Feiertage-Schleswig-Holstein-",Jahre,".html")
    #Fubnktioniert irgendwie nicht
    site = str_trim(site)
    #zwei mal
    site = str_replace(site, " ", "")
    site = str_replace(site, " ", "")
    #oder     aus dem Skript
    site = str_replace_all(site,"^[ \\s]+|[ \\s]+$", "")


#Ausgabe Prüfen
#print(site)
#Ausgabe: 
#[1] "https://www.schnelle-online.info/Schleswig-Holstein/Feiertage-Schleswig-Holstein-2013.html"
#[1] "https://www.schnelle-online.info/Schleswig-Holstein/Feiertage-Schleswig-Holstein-2014.html"
#[1] "https://www.schnelle-online.info/Schleswig-Holstein/Feiertage-Schleswig-Holstein-2015.html"
#[1] "https://www.schnelle-online.info/Schleswig-Holstein/Feiertage-Schleswig-Holstein-2016.html"
#[1] "https://www.schnelle-online.info/Schleswig-Holstein/Feiertage-Schleswig-Holstein-2017.html"
#[1] "https://www.schnelle-online.info/Schleswig-Holstein/Feiertage-Schleswig-Holstein-2018.html"
#[1] "https://www.schnelle-online.info/Schleswig-Holstein/Feiertage-Schleswig-Holstein-2019.html"

#Auffüllen des URL-Vectors    
#vector_url[i] = site


#Daten auslesen
htmlCode = read_html(site)

#print(htmlCode)
htmlCode = html_nodes(htmlCode,"tr:nth-child(9) .datum , tr:nth-child(9) .nounderline, :nth-child(8) .datum, :nth-child(8) .nounderline, tr:nth-child(7) .datum, tr:nth-child(7) .nounderline, :nth-child(6) .datum, :nth-child(6) .nounderline, tr:nth-child(5) .datum, tr:nth-child(5) .nounderline, :nth-child(4) .datum, :nth-child(4) .nounderline, #tablecolmid tr:nth-child(3) .datum, #tablecolmid tr:nth-child(3) .nounderline, .highlighthover tr:nth-child(1) .datum, .highlighthover tr:nth-child(1) .nounderline")

#Auffüllen des Inhalts-Vektors
#vector_inhalt[i] = htmlCode

#Data-Frame auffüllen
#websiteData[nrow(websiteData) + 1,] = c(Jahre, site, htmlCode)
#websiteData <- rbind(websiteData, data.frame(Jahr=Jahre, URL=site, Webseiteninhalt=htmlCode))  


htmlCode = str_replace_all(htmlCode,'<td class="datum">', "")
htmlCode = str_replace_all(htmlCode,"</td>", "")
htmlCode = str_replace_all(htmlCode,'<a class=\"nounderline\" href=\"/Feiertage/', "")
htmlCode = str_replace_all(htmlCode,"</a>", "")
htmlCode = str_replace_all(htmlCode,'html\">', "")


anzeige <-htmlCode
print(anzeige)
i = i+1
}







```

```{r Daten aus einer Kalender Webseite Teil 4, html-Code der Seite in eine Variable speichern}
# https://www.schnelle-online.info/Schleswig-Holstein/Feiertage-Schleswig-Holstein-2016.html


#Vektoren für die URL jeweils für URL und html Inhalt erstellen:
#vector_url <- c()
#vector_inhalt <- c()
#Data-Frame erstellen für die Datenspeicherung der Webseite
#websiteData <- data.frame(allYears, vector_url, vector_inhalt)
websiteData <- data.frame(matrix(ncol = 3, nrow = 0))
#Spalten benennen
colnames(websiteData) <- c('Jahr', 'URL', 'Webseiteninhalt')


#For-Schleife um jedes Jahr in allYears zu durchlaufen
i = 1
for(Jahre in allYears){
#Mit paste() Strings zusammensetzen  Url+ Jahreszahl aus der Variable allYears + rest der URL
#paste(String1,String2,String3)= String1String2String3  
    site=paste("http://www.feiertage-newsletter.de/deutschland/uebersicht-",Jahre,".html")
    #Fubnktioniert irgendwie nicht
    site = str_trim(site)
    #zwei mal
    site = str_replace(site, " ", "")
    site = str_replace(site, " ", "")
    #oder     aus dem Skript
    site = str_replace_all(site,"^[ \\s]+|[ \\s]+$", "")


#Ausgabe Prüfen
#print(site)


#Auffüllen des URL-Vectors    
#vector_url[i] = site


#Daten auslesen
htmlCode = read_html(site)

#print(htmlCode)
#htmlCode = html_nodes(htmlCode,".fz11_m13")
htmlCode <- cleanFun(htmlCode)
htmlCode <- str_match(htmlCode, "Datum\\s*(.*?)\\s*Silvester")



#Auffüllen des Inhalts-Vektors
#vector_inhalt[i] = htmlCode

#Data-Frame auffüllen
#websiteData[nrow(websiteData) + 1,] = c(Jahre, site, htmlCode)
#websiteData <- rbind(websiteData, data.frame(Jahr=Jahre, URL=site, Webseiteninhalt=htmlCode))  


#htmlCode = str_replace_all(htmlCode,'<table class="listfeiertage tableohneborder bgFAFAFA fz11_m13" cellpadding="0" cellspacing="0">\n<colgroup>\n<col width="1%">', "")
#htmlCode = str_replace_all(htmlCode,"</td>", "")
#htmlCode = str_replace_all(htmlCode,'<a class=\"nounderline\" href=\"/Feiertage/', "")
#htmlCode = str_replace_all(htmlCode,"</a>", "")
#htmlCode = str_replace_all(htmlCode,'html\">', "")
htmlCode <- cleanFun(htmlCode)

anzeige <-htmlCode
print(anzeige)
i = i+1
}







```
```{r}

tables = readHTMLTable("https://wiki.selfhtml.org/wiki/HTML/Tabellen/Aufbau_einer_Tabelle",which=1)
head(tables)


```

```{r Feiertage}




feiertage <- data.frame(matrix(ncol = 3, nrow = 0))


test = read_html("https://www.schulferien.org/Kalender_mit_Ferien/kalender_2013_ferien_Schleswig_Holstein.html")


test <- test %>% 
  html_nodes(".feiertag_liste") %>%
  html_text() %>% 
  .[1]

test = str_replace_all(test,"\n", "")
test = str_replace_all(test,"              2013", ".2013")

test = str_replace_all(test,"                                    ", "")
test = str_replace_all(test,"   ", "")

test = str_replace_all(test,"Jan", "01")
test = str_replace_all(test,"Feb", "02")
test = str_replace_all(test,"Mär", "03")
test = str_replace_all(test,"Apr", "04")
test = str_replace_all(test,"Mai", "05")
test = str_replace_all(test,"Jun", "06")
test = str_replace_all(test,"Jul", "07")
test = str_replace_all(test,"Aug", "08")
test = str_replace_all(test,"Sep", "09")
test = str_replace_all(test,"Okt", "10")
test = str_replace_all(test,"Nov", "11")
test = str_replace_all(test,"Dez", "12")

test = str_replace_all(test,"  ", ";") 
test = str_replace_all(test," ", "")  


rs <- (test)
rs = strsplit(rs, split = ";")
print(rs)

print(typeof(rs))


rs <-unlist(rs, use.names=FALSE);

print(rs)

#test = html_nodes(test,'//*[contains(concat( " ", @class, " " ), concat( " ", "kasten", " " ))]')
#test <- cleanFun(test)
print(test)


Datum <- vector();
Feiertag <- vector();
Jahr <- vector();

j = 1;
for(i in rs){
  if((j %% 2) != 0){
    Datum <- append(Datum,i);
    Jahr <- append(Jahr,"2013");
  }else{
    Feiertag <- append(Feiertag,i);
    
  }
  j = j + 1;
}

print(Datum);
print(Feiertag);


feiertage <- data.frame(Datum,Jahr,Feiertag)
```





```{r Ferien}

test = read_html("https://www.ferienkalender.com/ferien_deutschland/Schleswig-Holstein/2013-ferien-schleswig-holstein.htm")


test <- test %>% 
  html_nodes(".kasten") %>%
  html_text() %>% 
  .[1]



test = str_replace_all(test,"\n", "") 
test = str_replace_all(test,"Ferienkalender Schleswig-Holstein 2013Ferien 2013 im deutschen Bundesland Schleswig-Holstein:Winterferien-", "")
test = str_replace_all(test," / Frühjahrsferien", "") 
test = str_replace_all(test," - ", "2013 - ") 
test = str_replace_all(test,"Ferien 2013 für Schleswig-Holstein", "") 
test = str_replace_all(test,"ferien", "ferien ") 


rs <- (test)
rs = strsplit(rs, split = ";")
print(rs)


#test = html_nodes(test,'//*[contains(concat( " ", @class, " " ), concat( " ", "kasten", " " ))]')
#test <- cleanFun(test)
print(test)
```
















```{r Daten aus einer Kalender Webseite Teil 5, Auslesen/Aussortieren der Daten}

library(rvest)
library(xm12)

# https://www.schnelle-online.info/Schleswig-Holstein/Feiertage-Schleswig-Holstein-2016.html

site=

```

```{r}
Daten <- umsatzdaten %>%
  select(Datum, Warengruppe, Umsatz) %>% 
  
  for(datum in kiwo$Datum){
      
    KielerWoche = kiwo$KielerWoche
    Daten <- Daten %>% mutate(KielerWoche %in% kiwo)
  }
  



















fullData = data.frame(ITEM_GROUP = 
                       umsatzdaten,
                      select()
                      
                        )
                         

  
Feiertage
Schulferien
wetterBevoelkt
wetterSonnig
```









































































